export const seatErrorCodes = {
  SEAT_NOT_FOUND: 'SEAT_NOT_FOUND',
  SEAT_ALREADY_RESERVED: 'SEAT_ALREADY_RESERVED',
  SEAT_NOT_AVAILABLE: 'SEAT_NOT_AVAILABLE',
  MAX_SEATS_EXCEEDED: 'MAX_SEATS_EXCEEDED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export type SeatServiceError = keyof typeof seatErrorCodes;
